package com.github.vladimirlisovskij.simple_mocker.core.design

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF326B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F967)
val md_theme_light_onPrimaryContainer = Color(0xFF0B2000)
val md_theme_light_secondary = Color(0xFF316B12)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB1F58B)
val md_theme_light_onSecondaryContainer = Color(0xFF072100)
val md_theme_light_tertiary = Color(0xFF006D42)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7DFAB4)
val md_theme_light_onTertiaryContainer = Color(0xFF002110)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFDFDF5)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inverseSurface = Color(0xFF2F312C)
val md_theme_light_inversePrimary = Color(0xFF89DB4E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF326B00)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF89DB4E)
val md_theme_dark_onPrimary = Color(0xFF173800)
val md_theme_dark_primaryContainer = Color(0xFF245100)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F967)
val md_theme_dark_secondary = Color(0xFF96D872)
val md_theme_dark_onSecondary = Color(0xFF123800)
val md_theme_dark_secondaryContainer = Color(0xFF1D5200)
val md_theme_dark_onSecondaryContainer = Color(0xFFB1F58B)
val md_theme_dark_tertiary = Color(0xFF5FDD9A)
val md_theme_dark_onTertiary = Color(0xFF003920)
val md_theme_dark_tertiaryContainer = Color(0xFF005230)
val md_theme_dark_onTertiaryContainer = Color(0xFF7DFAB4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_outline = Color(0xFF8E9286)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val md_theme_dark_inversePrimary = Color(0xFF326B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF89DB4E)
val md_theme_dark_outlineVariant = Color(0xFF44483E)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF489500)
